Updates for linchpin 1.0.4 compatibility
* cinch/bin - The 'cinchpin' command has been fully removed and
deprecated.  cinch and linchpin are tracking different versions of
Ansible and cannot live in the same Python virtualenv, hence the need to
remove this convenience wrapper.  The new 'teardown' command is now
available to assist with removing Jenkins slaves from Jenkins masters.
This functionality was previously provided by 'cinchpin'.  Thanks to
greg-hellings for providing the code for this.

* cinch/playbooks/install-rhel7.yml - we now create two separate
virtualenvs for linchpin and cinch

* cinch/playbooks/install-rhel7.yml - the Python virtualenv creation
process has been stramlined by using native Ansible to work around
issues with the selinux Python module and outdated versions of pip and
setuptools

* cinch/playbooks/install-rhel7.yml - the Beaker Python package is no
longer installed in the virtualenv since with system-site-packages we
can use the Beaker version that's installed via RPM

* cinch/playbooks/install-rhel7.yml - the 'latest tip' install option
has been removed.  This is a developer tool that's no longer necessary
at this time

* Sphinx docs have been updated to reflect the changes in this commit

* All references to 'linch-pin' have been changed to 'linchpin' as the
project has been renamed

* jjb/ci-jslave-project-sample.yaml - This example template now uses the
two separate Python virtualenvs for linchpin and cinch

* jjb/ci-jslave-project-sample.yaml - The Jenkins jobs have been renamed
for less visual clutter

* jjb/ci-jslave-project-sample.yaml - A bug with teardown has been
fixed, where teardown would fail if the Jenkins slave never connected to
the Jenkins master

* jjb/install-rhel7.yml - Removed options for 'latest tip' and 'beaker'
to corresponded with the related Ansible playbook changes described
previously

* setup.py - Bumped version to 0.9.0

* setup.py - Replaced 'cinchpin' command entry point with new 'teardown'
command

* setup.py - Removed linchpin as a dependency

diff --git a/jjb/ci-jslave-project-sample.yaml b/jjb/ci-jslave-project-sample.yaml
--- a/jjb/ci-jslave-project-sample.yaml
+++ b/jjb/ci-jslave-project-sample.yaml
@@ -1,6 +1,7 @@
 ---
 - job-template:
-    name: 'jslave-{project}-{topology}-1-provision'
+    name: '{project}-{topology}-provision'
+    description: '{description}'
     defaults: cinch-topology-setup
     node: master
     parameters:
@@ -12,8 +13,13 @@
     builders:
       - shell: |
             #!/bin/bash -ex
+            source "${{JENKINS_HOME}}/opt/linchpin/bin/activate"
+            linchpin -v --creds-path {topology_path}/${{PROVIDER}}/credentials -w {topology_path}/${{PROVIDER}} up
+            deactivate
+
             source "${{JENKINS_HOME}}/opt/cinch/bin/activate"
-            cinchpin up -w {topology_path}/${{PROVIDER}}
+            cinch {topology_path}/${{PROVIDER}}/inventories/cinch-test.inventory
+            deactivate
     publishers:
       - archive:
           artifacts: '{topology_path}/${{PROVIDER}}/inventories/cinch-test.inventory'
@@ -22,17 +28,18 @@
           artifacts: '{topology_path}/${{PROVIDER}}/resources/cinch-test.output'
           allow-empty: 'true'
       - trigger-parameterized-builds:
-          - project: 'jslave-{project}-{topology}-2-runtest'
+          - project: '{project}-{topology}-runtest'
             current-parameters: true
             condition: 'SUCCESS'
             fail-on-missing: true
-          - project: 'jslave-{project}-{topology}-3-teardown'
+          - project: '{project}-{topology}-teardown'
             current-parameters: true
             condition: 'UNSTABLE_OR_WORSE'
             fail-on-missing: true
 
 - job-template:
-    name: 'jslave-{project}-{topology}-2-runtest'
+    name: '{project}-{topology}-runtest'
+    description: '{description}'
     node: '{jslave_name}'
     builders:
       - shell: |
@@ -43,42 +50,58 @@
           artifacts: 'test_artifact.txt'
           allow-empty: 'false'
       - trigger-parameterized-builds:
-          - project: 'jslave-{project}-{topology}-3-teardown'
+          - project: '{project}-{topology}-teardown'
             current-parameters: true
 
 - job-template:
-    name: 'jslave-{project}-{topology}-3-teardown'
+    name: '{project}-{topology}-teardown'
+    description: '{description}'
     defaults: cinch-topology-setup
     node: master
     builders:
       - copyartifact:
-          project: 'jslave-{project}-{topology}-1-provision'
+          project: '{project}-{topology}-provision'
           filter: '{topology_path}/${{PROVIDER}}/inventories/cinch-test.inventory'
           target: '{topology_path}/${{PROVIDER}}/inventories'
           flatten: true
       - copyartifact:
-          project: 'jslave-{project}-{topology}-1-provision'
+          project: '{project}-{topology}-provision'
           filter: '{topology_path}/${{PROVIDER}}/resources/cinch-test.output'
           target: '{topology_path}/${{PROVIDER}}/resources'
           flatten: true
       - shell: |
             #!/bin/bash -ex
             source "${{JENKINS_HOME}}/opt/cinch/bin/activate"
-            cinchpin destroy -w {topology_path}/${{PROVIDER}}
+            # Try to remove the Jenkins slave from the Jenkins master, but do not fail
+            # the entire teardown job if Jenkins slave disconnection cannot be done.
+            # This is for cases where the provision step failed to attach the slave,
+            # but the instance should still be destroyed by linchpin.
+            set +e
+            teardown {topology_path}/${{PROVIDER}}/inventories/cinch-test.inventory
+            set -e
+            deactivate
+
+            source "${{JENKINS_HOME}}/opt/linchpin/bin/activate"
+            linchpin -v --creds-path {topology_path}/${{PROVIDER}}/credentials -w {topology_path}/${{PROVIDER}} destroy
+            deactivate
 
 - job-group:
-    name: jslave-provision-runtest-teardown
+    name: provision-runtest-teardown
     jobs:
-      - 'jslave-{project}-{topology}-1-provision'
-      - 'jslave-{project}-{topology}-2-runtest'
-      - 'jslave-{project}-{topology}-3-teardown'
+      - '{project}-{topology}-provision'
+      - '{project}-{topology}-runtest'
+      - '{project}-{topology}-teardown'
 
 - project:
-    name: jslave-cinch-jobs
+    name: cinch-jobs
     project: cinch
     topology:
       - example
     jobs:
-      - jslave-provision-runtest-teardown
+      - provision-runtest-teardown
     jslave_name: cinch-slave
-    topology_path: 'cinch-example/examples/linch-pin-topologies'
+    topology_path: 'cinch-example/examples/linchpin-topologies'
+    description: |
+        cinch Jenkins slave provisioning example workflow using Jenkins Job Builder
+
+        https://github.com/RedHatQE/cinch/blob/master/jjb/ci-jslave-project-sample.yaml
